## Data Cleaning

I am cleaning NYC Open Data's [Bus Delays and Breakdown](https://data.cityofnewyork.us/Transportation/Bus-Breakdown-and-Delays/ez4e-fazm) dataset using Python in order to create more beautiful visualizations of the data using p5.js for my Data Visualization class. you can check out some of my work [here](http://navierula.github.io/A4892.html).

In [61]:
import pandas as pd

In [62]:
# import dataset
df = pd.read_csv("data/Bus_Breakdown_and_Delays.csv", sep=",")

In [63]:
# length of dataset initially
len(df)

198746

In [64]:
# print first 5 rows of dataset
df.head(5)

,School_Year,Busbreakdown_ID,Run_Type,Bus_No,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Boro,Bus_Company_Name,How_Long_Delayed,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK
0,2015-2016,1227538,Special Ed AM Run,2621,J711,Heavy Traffic,75003,11/5/15 8:10,11/5/15 8:12,New Jersey,"RELIANT TRANS, INC. (B232",NaN,11,Yes,No,Yes,11/5/15 8:12,11/5/15 8:12,Running Late,School-Age
1,2015-2016,1227539,Special Ed AM Run,1260,M351,Heavy Traffic,6716,11/5/15 8:10,11/5/15 8:12,Manhattan,HOYT TRANSPORTATION CORP.,20MNS,2,Yes,Yes,No,11/5/15 8:12,11/5/15 8:13,Running Late,School-Age
2,2015-2016,1227540,Pre-K/EI,418,3,Heavy Traffic,C445,11/5/15 8:09,11/5/15 8:13,Bronx,"G.V.C., LTD.",15MIN,8,Yes,Yes,Yes,11/5/15 8:13,11/5/15 8:13,Running Late,Pre-K
3,2015-2016,1227541,Special Ed AM Run,4522,M271,Heavy Traffic,2699,11/5/15 8:12,11/5/15 8:14,Manhattan,"RELIANT TRANS, INC. (B232",15 MIN,6,No,No,No,11/5/15 8:14,11/5/15 8:14,Running Late,School-Age
4,2015-2016,1227542,Special Ed AM Run,3124,M373,Heavy Traffic,2116,11/5/15 8:13,11/5/15 8:14,Manhattan,"RELIANT TRANS, INC. (B232",NaN,6,No,No,No,11/5/15 8:14,11/5/15 8:14,Running Late,School-Age

In [65]:
# drop all rows with missing values
df = df.dropna(how='any',axis=0)

### Cleaning Time

The "How_Long_Delayed" column contains times in varying formats. My aim is to standardize all these times to minutes and to integer variables instead of strings.

Formats that delay times could appear in:
- 15
- 15MIN
- 20-30 MINUTES
- 10/15 mins
- 1hr
- 1/2 HOUR
- 1hr????
- ONE HOUR
- HA 9944

Edge Cases for Hours
- half hour
- IHR40MIN
- ONE HOUR
- HA 9944
- HR1
- one hour
- Half hour
- MORE THAN
- \1 hr-
- hour
- HOUR

Other cases can be seen in the code below.

In [35]:
# remove every odd, edge case 
# any value with unreadable formatting

df = df[df.How_Long_Delayed != "IHR40MIN"]
df = df[df.How_Long_Delayed != "HA 9944"]
df = df[df.How_Long_Delayed != "1403"]
df = df[df.How_Long_Delayed != "@least 1/2"]
df = df[df.How_Long_Delayed != "2O MINS"]
df = df[df.How_Long_Delayed != "3o min"]
df = df[df.How_Long_Delayed != "3O MIN"]
df = df[df.How_Long_Delayed != "6O MIN"]
df = df[df.How_Long_Delayed != "0.3"]
df = df[df.How_Long_Delayed != "0-15 Min"]
df = df[df.How_Long_Delayed != "-10"]

df = df[df.How_Long_Delayed != "HR1"]
df = df[df.How_Long_Delayed != "m579"]
df = df[df.How_Long_Delayed != "bqe"]
df = df[df.How_Long_Delayed != "NI0634"]
df = df[df.How_Long_Delayed != "NI0306"]
df = df[df.How_Long_Delayed != "NI2134"]
df = df[df.How_Long_Delayed != "NI0627"]
df = df[df.How_Long_Delayed != "NI932"]
df = df[df.How_Long_Delayed != "NI0933"]
df = df[df.How_Long_Delayed != "accident"]

df = df[df.How_Long_Delayed != "TBD"]
df = df[df.How_Long_Delayed != "MORE THAN"]
df = df[df.How_Long_Delayed != "DUE TO SNO"]
df = df[df.How_Long_Delayed != "traffic"]
df = df[df.How_Long_Delayed != "TRAFFIC"]
df = df[df.How_Long_Delayed != "UNSURE"]
df = df[df.How_Long_Delayed != "unknown"]
df = df[df.How_Long_Delayed != "UNKNOWN"]
df = df[df.How_Long_Delayed != "Danny"]

df = df[df.How_Long_Delayed != "est. 10-15"]
df = df[df.How_Long_Delayed != "est. 25min"]
df = df[df.How_Long_Delayed != "est.35min"]
df = df[df.How_Long_Delayed != "est. 12min"]
df = df[df.How_Long_Delayed != "est.9:15am"]
df = df[df.How_Long_Delayed != "est. 20min"]
df = df[df.How_Long_Delayed != "Est.20-30m"]
df = df[df.How_Long_Delayed != "est.20 min"]
df = df[df.How_Long_Delayed != "est. 20min"]
df = df[df.How_Long_Delayed != "est.15-20m"]
df = df[df.How_Long_Delayed != "est. 30min"]
df = df[df.How_Long_Delayed != "est. 35min"]

df = df[df.How_Long_Delayed != "1.5"]
df = df[df.How_Long_Delayed != "1:00"]
df = df[df.How_Long_Delayed != "1:20MIN"]

df = df[df.How_Long_Delayed != "2-Jan"]
df = df[df.How_Long_Delayed != "15-Oct"]

df = df[df.How_Long_Delayed != "40m1in????"]
df = df[df.How_Long_Delayed != "mins"]
df = df[df.How_Long_Delayed != "MIN"]
df = df[df.How_Long_Delayed != "MINS"]
df = df[df.How_Long_Delayed != "mint"]
df = df[df.How_Long_Delayed != "minutes"]
df = df[df.How_Long_Delayed != "MNS"]

df = df[df.How_Long_Delayed != "MAYBE 1/2"]
df = df[df.How_Long_Delayed != "\\1 hr-"]
df = df[df.How_Long_Delayed != "!0 mins"]
df = df[df.How_Long_Delayed != "??? 60 min"]
df = df[df.How_Long_Delayed != "1:30?mins"]

df = df[df.How_Long_Delayed != "?"]
df = df[df.How_Long_Delayed != "??"]
df = df[df.How_Long_Delayed != "???"]
df = df[df.How_Long_Delayed != "????"]
df = df[df.How_Long_Delayed != "?????"]
df = df[df.How_Long_Delayed != "??????"]
df = df[df.How_Long_Delayed != "???????"]
df = df[df.How_Long_Delayed != "????????"]
df = df[df.How_Long_Delayed != "??????????"]
df = df[df.How_Long_Delayed != "?????????"]

df = df[df.How_Long_Delayed != "_"]
df = df[df.How_Long_Delayed != "_______"]
df = df[df.How_Long_Delayed != "------"]
df = df[df.How_Long_Delayed != "-------"]
df = df[df.How_Long_Delayed != "----------"]

df = df[df.How_Long_Delayed != "unk"]

In [36]:
# check current length of dataframe
len(df)

156084

In [37]:
# create acceptable list for minute values to compare against values
# in the dataset
nums = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
       "10", "11", "12", "13", "14", "15", "16", "17", "18",
       "19", "20", "21", "22", "23", "24", "25", "26", "27",
       "28", "29", "30", "31", "32", "33", "34", "35", "36",
       "37", "38", "39", "40", "41", "42", "43", "44", "45",
       "46", "47", "48", "49", "50", "51", "52", "53", "54",
       "55", "56", "57", "58", "59", "60"]

In [38]:
# check for more edge cases and append result to a list

how_long_delayed = []

for i, j in df["How_Long_Delayed"].iteritems():
    if j[0:3] == "1/2":
        how_long_delayed.append(30)
    elif len(j) > 2 and ("h" in j or "H" in j) and j[0:2] =="45":
        how_long_delayed.append(45)
    elif len(j) > 2 and ("half" in j or "Half" in j):
        how_long_delayed.append(30)
    elif j == "1 hourhalf":
        how_long_delayed.append(90)
    elif j == "hour" or j == "HOUR":
        how_long_delayed.append(60)
    elif j[0:3] == "one" or j[0:3] == "ONE":
        how_long_delayed.append(60)
    elif len(j) > 2 and ("h" in j or "H" in j) and j[0].isdigit():
        how_long_delayed.append(int(j[0])*60)
    elif j == "1HR":
        how_long_delayed.append(60)
    elif j == "1 HR":
        how_long_delayed.append(60)
    elif j == "1 hr":
        how_long_delayed.append(60)
    elif j == "1 HOUR":
        how_long_delayed.append(60)
    elif j == "1 hour":
        how_long_delayed.append(60)
    elif j == "1hr/30min":
        how_long_delayed.append(60)
    elif j == "10/15MINS":
        how_long_delayed.append(10)
    elif str(j[0:2]) in nums:
        how_long_delayed.append(int(j[0:2]))
    elif len(j) == 1 and j in nums or len(j) == 2 and j in nums:
        how_long_delayed.append(int(j))
    elif len(j) == 1:
        how_long_delayed.append(int(j))
    elif len(j) >= 3 and (j[2] == "m" or j[2] == "M"):
        how_long_delayed.append(int(j[0]))
    elif len(j) >= 4 and (j[3] == "m" or j[3] == "M") and j[0:2] != "5-" \
    and j[0:2] != "6-" and j[0:2] != "7-" and j[0:2] != '4/' \
    and j[0:2] != '3.':
        how_long_delayed.append(int(j[0:2]))
    else:
        how_long_delayed.append(j)

In [39]:
# add more clarity to previously cleaned list

how_long_delayed_v2 = []

for item in how_long_delayed:
    if type(item) == str and item[0:2] in nums:
        how_long_delayed_v2.append(int(item[0:2]))
    elif type(item) == str and (item == "1HR" or item == "1 HOUR" or item == "1 HR" or item == "1 Hr"):
        how_long_delayed_v2.append(60)
    elif type(item) == str and len(item) >= 3 and item[1].isdigit() and item[0].isdigit():
            how_long_delayed_v2.append(int(item[0:2]))
    elif type(item) == str and item[0] == "8":
        how_long_delayed_v2.append(8)
    elif type(item) == str and item[0] == "7":
        how_long_delayed_v2.append(7)
    elif type(item) == str and item[0] == "6":
        how_long_delayed_v2.append(6)
    elif type(item) == str and item[0] == "5":
        how_long_delayed_v2.append(5)
    elif type(item) == str and item[0] == "4":
        how_long_delayed_v2.append(4)
    elif type(item) == str and item[0] == "3":
        how_long_delayed_v2.append(3)
    elif type(item) == str and item[0] == "2":
        how_long_delayed_v2.append(2)
    elif type(item) == str and item[0:2] == "90":
        how_long_delayed_v2.append(90)
    elif type(item) == str and item[0] == "9":
        how_long_delayed_v2.append(9)
    elif type(item) == str and item == "1H":
        how_long_delayed_v2.append(60)
    elif type(item) == str and item == "1MNS":
        how_long_delayed_v2.append(1)
    elif type(item) == str and item == "1/ 15 min":
        how_long_delayed_v2.append(75)
    elif type(item) == str and item == ".45 minute":
        how_long_delayed_v2.append(45)
    elif type(item) == str and item == "1:40 MINS":
        how_long_delayed_v2.append(100)
    elif type(item) == str and item == "1 20 min":
        how_long_delayed_v2.append(80)
    elif type(item) == str and (item == "1 30 min" or item == "1 1/2" \
                               or item == ".30-45" or item == "1:30 min" \
                               or item == "1 30mnts"):
        how_long_delayed_v2.append(90)
    
    else:
        how_long_delayed_v2.append(item)

In [40]:
# check length of final list
len(how_long_delayed_v2)

156084

In [41]:
# drop original How_Long_Delayed column
df = df.drop("How_Long_Delayed", 1)

In [42]:
# print first 5 rows of dataset with cleaned time values
df.head(5)

,School_Year,Busbreakdown_ID,Run_Type,Bus_No,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Boro,Bus_Company_Name,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK
1,2015-2016,1227539,Special Ed AM Run,1260,M351,Heavy Traffic,6716,11/5/15 8:10,11/5/15 8:12,Manhattan,HOYT TRANSPORTATION CORP.,2,Yes,Yes,No,11/5/15 8:12,11/5/15 8:13,Running Late,School-Age
2,2015-2016,1227540,Pre-K/EI,418,3,Heavy Traffic,C445,11/5/15 8:09,11/5/15 8:13,Bronx,"G.V.C., LTD.",8,Yes,Yes,Yes,11/5/15 8:13,11/5/15 8:13,Running Late,Pre-K
3,2015-2016,1227541,Special Ed AM Run,4522,M271,Heavy Traffic,2699,11/5/15 8:12,11/5/15 8:14,Manhattan,"RELIANT TRANS, INC. (B232",6,No,No,No,11/5/15 8:14,11/5/15 8:14,Running Late,School-Age
5,2015-2016,1227543,Special Ed AM Run,HT1502,W796,Heavy Traffic,75407,11/5/15 7:58,11/5/15 8:14,Westchester,CHILDREN`S TRANS INC. (B2,1,Yes,Yes,Yes,11/5/15 8:14,11/5/15 8:14,Running Late,School-Age
6,2015-2016,1227544,Special Ed AM Run,142,W633,Heavy Traffic,75670,11/5/15 8:24,11/5/15 8:15,Westchester,MAR-CAN TRANSPORT CO. INC,3,Yes,No,No,11/5/15 8:15,11/5/15 8:16,Running Late,School-Age

In [43]:
# add cleaned column as How_Long_Delayed
df['How_Long_Delayed'] = how_long_delayed_v2

In [44]:
# print dataset tail, new column is added to the end of the dataset
df.tail(5)

,School_Year,Busbreakdown_ID,Run_Type,Bus_No,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Boro,Bus_Company_Name,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK,How_Long_Delayed
198740,2016-2017,1337850,Pre-K/EI,118,3,Heavy Traffic,C037,4/4/17 7:55,4/4/17 8:03,Bronx,"G.V.C., LTD.",8,Yes,Yes,No,4/4/17 8:03,4/4/17 8:03,Running Late,Pre-K,15
198741,2016-2017,1338452,Pre-K/EI,9345,2,Heavy Traffic,C530,4/5/17 8:00,4/5/17 8:10,Bronx,"G.V.C., LTD.",7,Yes,Yes,No,4/5/17 8:10,4/5/17 8:10,Running Late,Pre-K,15
198742,2016-2017,1341521,Pre-K/EI,1,5,Heavy Traffic,C579,4/24/17 7:42,4/24/17 7:44,Bronx,"G.V.C., LTD.",0,Yes,Yes,No,4/24/17 7:44,4/24/17 7:44,Running Late,Pre-K,20
198743,2016-2017,1353044,Special Ed PM Run,GC0112,X928,Heavy Traffic,9003,5/25/17 16:22,5/25/17 16:28,Bronx,G.V.C. LTD. (B2192),0,Yes,Yes,Yes,5/25/17 16:28,5/25/17 16:34,Running Late,School-Age,20
198745,2016-2017,1353046,Project Read PM Run,2530,K617,Other,21436,5/25/17 16:36,5/25/17 16:37,Brooklyn,"RELIANT TRANS, INC. (B232",7,Yes,Yes,Yes,5/25/17 16:37,5/25/17 16:37,Running Late,School-Age,45

### Cleaning Bus Company Names

In [45]:
# list all bus company names in order
sorted(list(df.Bus_Company_Name.unique()))

['ACME BUS CORP. (B2321)',
 'ADDIES',
 'ALINA SERVICES CORP.',
 'ALL AMERICAN SCHOOL BUS C',
 'ALL AMERICAN SCHOOL BUS CORP.',
 'ALL COUNTY BUS LLC (B2321',
 'ALL COUNTY BUS LLC (B2321)',
 'ALLIED TRANSIT CORP.',
 'ANOTHER RIDE INC.',
 'B & F SKILLED INC.(B2192)',
 'BOBBY`S BUS CO. INC.',
 'BORO TRANSIT, INC.',
 'CAREFUL BUS',
 'CAREFUL BUS SERVICE INC (',
 'CAREFUL BUS SERVICE INC (B2192)',
 'CHILDREN`S TRANS INC. (B2',
 'CHILDREN`S TRANS INC. (B2321)',
 'CONSOLIDATED BUS TRANS. I',
 'CONSOLIDATED BUS TRANS. INC.',
 'DON THOMAS BUSES, INC.',
 'DON THOMAS BUSES, INC. (B',
 'DON THOMAS BUSES, INC. (B2321)',
 'Don Thomas Buses',
 'EMPIRE CHARTER SERVICE IN',
 'EMPIRE CHARTER SERVICE INC',
 'EMPIRE STATE BUS CORP.',
 'FIRST STEPS',
 'FIRST STEPS TRANSP INC. (',
 'FIRST STEPS TRANSP INC. (B2192)',
 'FORTUNA BUS COMPANY',
 'G.V.C. LTD. (B2192)',
 'G.V.C., LTD.',
 'GRANDPA`S BUS CO., INC.',
 'HAPPY CHILD TRANS LLC (B2',
 'HAPPY CHILD TRANS LLC (B2192)',
 'HOYT TRANSPORTATION CORP.',
 'I & Y TRANSIT CORP',
 'IC BUS INC. (PRE-K)',
 'JOFAZ TRANSPORTATION INC.',
 'L & M BUS CORP (A)',
 'L & M BUS CORP.',
 'L & M BUS CORP. (B2192)',
 'L & M BUS CORP. (B2321)',
 'LEESEL TRANSP CORP (B2192',
 'LEESEL TRANSP CORP (B2192)',
 'LITTLE LINDA BUS CO.,INC.',
 'LITTLE LISA BUS CO. INC.',
 'LITTLE RICHIE BUS SERVICE',
 'LOGAN BUS COMPANY INC.',
 'LOGAN TRANSPORTATION SYST',
 'LOGAN TRANSPORTATION SYSTEMS',
 'LORINDA ENT. LTD.',
 'LORISSA BUS SERVICE INC.',
 'MAR-CAN TRANSPORT CO. INC',
 'MAR-CAN TRANSPORT CO. INC (B2192)',
 'MJT BUS',
 'MONTAUK STUDENT TRANS LLC',
 'MONTAUK STUDENT TRANS, IN',
 'MONTAUK STUDENT TRANS, INC. (B2321)',
 'MUTUAL BUS CORP. (B2192)',
 'MUTUAL BUS CORP. (B2321)',
 'MV TRANSPORTATION, INC.',
 'NEW DAWN TRANSIT, LLC (B2',
 'NEW DAWN TRANSIT, LLC (B2321)',
 'PENNY TRANSPORTATION',
 'PHILLIP BUS CORP (B2192)',
 'PHILLIPS BUS SERVICE',
 'PIONEER TRANSPORTATION CO',
 'PIONEER TRANSPORTATION CORP',
 'PRIDE TRANSPORTATION (SCH',
 'PRIDE TRANSPORTATION (SCH AGE)',
 'QUALITY TRANSPORTATION CO',
 'QUALITY TRANSPORTATION CORP.',
 'R & C TRANSIT, INC. (B232',
 'RELIANT TRANS, INC.',
 'RELIANT TRANS, INC. (B232',
 'RELIANT TRANS, INC. (B2321)',
 'SAFE COACH INC.',
 'SAFE COACH INC. (B2321)',
 'SELBY TRANS CORP. (B2192)',
 'SELBY TRANSPORTATION',
 'SMART PICK',
 'SNT BUS INC',
 'THIRD AVENUE TRANSIT',
 'THOMAS BUSES INC (B2192)',
 'THOMAS BUSES, INC.',
 'THOMAS BUSES, INC. (B2321',
 'THOMAS BUSES, INC. (B2321)',
 'TWENTY FIRST AV TRANSP (B',
 'TWENTY FIRST AV TRANSP (B2192)',
 'VAN TRANS LLC',
 'VAN TRANS LLC (B2192)',
 'VINNY`S BUS SERVICES (B23',
 'VINNY`S BUS SERVICES (B2321)',
 'Y & M TRANSIT CORP (B2192',
 'Y & M TRANSIT CORP (B2192)',
 'Y & M TRANSIT CORP (B2321',
 'Y & M TRANSIT CORP (B2321)',
 '`',
 'gvc',
 'phillip bus service']

In [46]:
# remove weird/blank bus names from dataset
df = df[df.Bus_Company_Name != "`"]

In [47]:
len(df)

156083

In [48]:
# define variable to hold bus company names in dataset
bus_comp_names = list(df.Bus_Company_Name)

In [49]:
len(bus_comp_names)

156083

In [50]:
bus_company_names = []

for item in bus_comp_names:
    if item == "ACME BUS CORP. (B2321)":
        bus_company_names.append("ACME BUS CORP.")
    elif item == "ALL AMERICAN SCHOOL BUS C":
        bus_company_names.append("ALL AMERICAN SCHOOL BUS CORP.")
    elif item == "ALL COUNTY BUS LLC (B2321" or item == "ALL COUNTY BUS LLC (B2321)":
        bus_company_names.append("ALL COUNTY BUS LLC")
    elif item == "BOBBY`S BUS CO. INC.":
        bus_company_names.append("BOBBY'S BUS CO. INC.")
    elif item == "CAREFUL BUS" or item == "CAREFUL BUS SERVICE INC (" or item == "CAREFUL BUS SERVICE INC (B2192)":
        bus_company_names.append("CAREFUL BUS SERVICE INC.")
    elif item == "CHILDREN`S TRANS INC. (B2" or item == "CHILDREN`S TRANS INC. (B2321)":
        bus_company_names.append("CHILDREN'S TRANS. INC.")
    elif item == "CONSOLIDATED BUS TRANS. I":
        bus_company_names.append("CONSOLIDATED BUS TRANS. INC.")
    elif item == "DON THOMAS BUSES, INC. (B" or item == "DON THOMAS BUSES, INC. (B2321)" or item == "Don Thomas Buses":
        bus_company_names.append("DON THOMAS BUSES, INC.")
    elif item == "EMPIRE CHARTER SERVICE IN" or item == "EMPIRE CHARTER SERVICE INC":
        bus_company_names.append("EMPIRE CHARTER SERVICE INC.")
    elif item == "FIRST STEPS" or item == "FIRST STEPS TRANSP INC. (" or item == "FIRST STEPS TRANSP INC. (B2192)":
        bus_company_names.append("FIRST STEPS TRANS. INC.")
    elif item == "G.V.C. LTD. (B2192)" or item == "gvc":
        bus_company_names.append("G.V.C., LTD.")
    elif item == "GRANDPA`S BUS CO., INC.":
        bus_company_names.append("GRANDPA'S BUS CO., INC.")
    elif item == "HAPPY CHILD TRANS LLC (B2" or item == "HAPPY CHILD TRANS LLC (B2192)":
        bus_company_names.append("HAPPY CHILD TRANS. LLC")
    elif item == "I & Y TRANSIT CORP":
        bus_company_names.append("I & Y TRANSIT CORP.")
    elif item == "L & M BUS CORP (A)" or item == "L & M BUS CORP. (B2192)" or item == "L & M BUS CORP. (B2321)":
        bus_company_names.append("L & M BUS CORP.")
    elif item == "LEESEL TRANSP CORP (B2192" or item == "LEESEL TRANSP CORP (B2192)":
        bus_company_names.append("LEESEL TRANS. CORP.")
    elif item == "LITTLE LINDA BUS CO.,INC.":
        bus_company_names.append("LITTLE LINDA BUS CO., INC.")
    elif item == "LITTLE LISA BUS CO. INC.":
        bus_company_names.append("LITTLE LISA BUS CO., INC.")
    elif item == "LOGAN TRANSPORTATION SYST":
        bus_company_names.append("LOGAN TRANSPORTATION SYSTEMS")
    elif item == "MAR-CAN TRANSPORT CO. INC (B2192)" or item == "MAR-CAN TRANSPORT CO. INC":
        bus_company_names.append("MAR-CAN TRANSPORT CO. INC.")
    elif item == "MONTAUK STUDENT TRANS, IN" or item == "MONTAUK STUDENT TRANS LLC" or item == "MONTAUK STUDENT TRANS, INC. (B2321)":
        bus_company_names.append("MONTAUK STUDENT TRANS. LLC")
    elif item == "MUTUAL BUS CORP. (B2192)" or item == "MUTUAL BUS CORP. (B2321)":
        bus_company_names.append("MUTUAL BUS CORP.")
    elif item == "NEW DAWN TRANSIT, LLC (B2" or item == "NEW DAWN TRANSIT, LLC (B2321)":
        bus_company_names.append("NEW DAWN TRANSIT, LLC")
    elif item == "PHILLIP BUS CORP (B2192)":
        bus_company_names.append("PHILLIP BUS CORP.")
    elif item == "phillip bus service" or item == "PHILLIPS BUS SERVICE":
        bus_company_names.append("PHILLIP BUS SERVICE")
    elif item == "PIONEER TRANSPORTATION CO" or item == "PIONEER TRANSPORTATION CORP":
        bus_company_names.append("PIONEER TRANSPORTATION CORP.")
    elif item == "PRIDE TRANSPORTATION (SCH" or item == "PRIDE TRANSPORTATION (SCH AGE)":
        bus_company_names.append("PRIDE TRANSPORTATION")
    elif item == "QUALITY TRANSPORTATION CO":
        bus_company_names.append("QUALITY TRANSPORTATION CORP.")
    elif item == "R & C TRANSIT, INC. (B232":
        bus_company_names.append("R & C TRANSIT, INC.")
    elif item == "RELIANT TRANS, INC. (B232" or item == "RELIANT TRANS, INC. (B2321)":
        bus_company_names.append("RELIANT TRANS, INC.")
    elif item == "SAFE COACH INC. (B2321)":
        bus_company_names.append("SAFE COACH INC.")
    elif item == "SELBY TRANS CORP. (B2192)" or item == "SELBY TRANSPORTATION":
        bus_company_names.append("SELBY TRANS. CORP.")
    elif item == "SNT BUS INC":
        bus_company_names.append("SNT BUS INC.")
    elif item == "THOMAS BUSES INC (B2192)" or item == "THOMAS BUSES, INC. (B2321" or item == "THOMAS BUSES, INC. (B2321)":
        bus_company_names.append("THOMAS BUSES, INC.")
    elif item == "TWENTY FIRST AV TRANSP (B" or item == "TWENTY FIRST AV TRANSP (B2192)":
        bus_company_names.append("TWENTY FIRST AVENUE BUS CORP.")
    elif item == "VAN TRANS LLC (B2192)":
        bus_company_names.append("VAN TRANS LLC")
    elif item == "VINNY`S BUS SERVICES (B23" or item == "VINNY`S BUS SERVICES (B2321)":
        bus_company_names.append("VINNY'S BUS SERVICES")
    elif item == "Y & M TRANSIT CORP (B2192" or item == "Y & M TRANSIT CORP (B2192)" or item == "Y & M TRANSIT CORP (B2321" or item == "Y & M TRANSIT CORP (B2321)":
        bus_company_names.append("Y & M TRANSIT CORP.")
    else:
        bus_company_names.append(item)

In [51]:
# check length of bus company names
len(bus_company_names)

156083

In [52]:
# drop original Bus_Company column
df = df.drop("Bus_Company_Name", 1)

In [57]:
df['Bus_Company_Name'] = bus_company_names

In [58]:
# check that new column has been added
df.head(5)

,School_Year,Busbreakdown_ID,Run_Type,Bus_No,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Boro,...,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK,How_Long_Delayed,Bus_Comapany_Name,Bus_Company_Name
1,2015-2016,1227539,Special Ed AM Run,1260,M351,Heavy Traffic,6716,11/5/15 8:10,11/5/15 8:12,Manhattan,...,Yes,Yes,No,11/5/15 8:12,11/5/15 8:13,Running Late,School-Age,20,HOYT TRANSPORTATION CORP.,HOYT TRANSPORTATION CORP.
2,2015-2016,1227540,Pre-K/EI,418,3,Heavy Traffic,C445,11/5/15 8:09,11/5/15 8:13,Bronx,...,Yes,Yes,Yes,11/5/15 8:13,11/5/15 8:13,Running Late,Pre-K,15,"G.V.C., LTD.","G.V.C., LTD."
3,2015-2016,1227541,Special Ed AM Run,4522,M271,Heavy Traffic,2699,11/5/15 8:12,11/5/15 8:14,Manhattan,...,No,No,No,11/5/15 8:14,11/5/15 8:14,Running Late,School-Age,15,"RELIANT TRANS, INC.","RELIANT TRANS, INC."
5,2015-2016,1227543,Special Ed AM Run,HT1502,W796,Heavy Traffic,75407,11/5/15 7:58,11/5/15 8:14,Westchester,...,Yes,Yes,Yes,11/5/15 8:14,11/5/15 8:14,Running Late,School-Age,30,CHILDREN'S TRANS. INC.,CHILDREN'S TRANS. INC.
6,2015-2016,1227544,Special Ed AM Run,142,W633,Heavy Traffic,75670,11/5/15 8:24,11/5/15 8:15,Westchester,...,Yes,No,No,11/5/15 8:15,11/5/15 8:16,Running Late,School-Age,20,MAR-CAN TRANSPORT CO. INC.,MAR-CAN TRANSPORT CO. INC.

In [59]:
# export new and cleaned dataframe
df.to_csv("school_bus_delays_cleaned.csv")

In [60]:
# check current length of dataframe
len(df)

156083